import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const iranYekan = localFont({
  src: [
    {
      path: '../../public/fonts/yekan.eot',
      weight: '400',
    },
    {
      path: '../../public/fonts/yekan.woff',
      weight: '400',
    },
    {
      path: '../../public/fonts/yekan.ttf',
      weight: '400',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={iranYekan.className}>{children}</body>
    </html>
  )
}
